repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: check-docstring-first
      stages:
      - commit
      - push
    - id: check-merge-conflict
      stages:
      - push
    - id: double-quote-string-fixer
      stages:
      - commit
      - push
    - id: trailing-whitespace
      stages:
      - commit
      - push
    - id: end-of-file-fixer
      stages:
      - commit
      - push
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8
      stages:
        - commit
        - push
      args:
        - --max-line-length=120
        - --diff
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    - id: add-trailing-comma
      stages:
        - commit
        - push
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        stages:
          - commit
          - push
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        stages:
          - commit
          - push
        args:
          - --max-line-length=120
